### ISSUE TITLE
Could you share the test config yml files of testing NR IQA?

### ISSUE THREAD

**Issue by HannahJHan** [Luciennnnnnn/DualFormer#1]
Hi ! Thanks for your work!
Could you share the test config yml files which test_iqa.py needs? I can't run the scripts/test/test_iqa_dual_former.sh command due to the missing of the yml files.
Thanks so much!

https://github.com/Luciennnnnnn/DualFormer/blob/f0481da3cf768eacbbab0e1d813896c67f8f97a4/scripts/test_iqa.py#L61C53-L61C53

**Comment by Luciennnnnnn** [comment]
Hi, @HannahJHan, thank you for your interest in our work.

These configuration files are included in the [Google Cloud Drive](https://drive.google.com/drive/folders/1iGS32Qux9mr4SJt2Zb7XTv4Xq6zLEy6I?usp=drive_link) we provide, and you should download the content and place it in `experiments/pretrained_models`.

Feel free to reopen the issue if you have any other problems.
